[package]
name = "pagcrypto-dashboard-substreams"
version = "0.1.0"
edition = "2021"

[dependencies]
substreams = "0.5"
substreams-solana = "0.6"
prost = "0.11"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"
